### ISSUE TITLE
accessToken included twice in curl commandline

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback-component-explorer#172] opened 2016-08-11 19:52 UTC
For example, the curl line for a given "Paths" model is shown here with two entries of the accessToken, and usually this makes the server not behave properly (can get crashes where userId is referenced, etc...)

```
curl -X GET --header "Accept: application/json" "http://0.0.0.0:3000/api/Paths?type=media&access_token=vw5AieDAruaigAHGCzdQquKzWK1GVGzvmsARNDLz0Q5hEas8DKoAISzkpYdU1dj4&access_token=vw5AieDAruaigAHGCzdQquKzWK1GVGzvmsARNDLz0Q5hEas8DKoAISzkpYdU1dj4"
```

**Comment by azatoth** [comment] 2016-08-15 19:41
@richardpringle informed me I had filed the bug [strongloop/loopback-swagger#50] possibly in the wrong repo and propsed it was better to file it here instead.

**Comment by richardpringle** [comment] 2016-08-16 14:45
Thanks for pointing out the bug @azatoth!

**Comment by dmtux** [comment] 2016-11-30 13:43
I took last commit - https://github.com/dmtux/loopback-component-explorer/commit/2bcce529e57dc24d8b8350baa6addba2b88a9584 
And I can't reproduce this bug. May be fixed?

**Comment by superkhau** [comment] 2016-12-07 08:23
Closing as resolved, if you are still running into issues, please ping and we can reopen.

**Closed by superkhau** 2016-12-07 08:23 UTC
Labels: bug
